<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BookedAppointmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booked_appointments')->delete();
        
        \DB::table('booked_appointments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-09T10:31:19.593Z',
                'start_time' => '04:41 PM',
                'end_time' => '05:00 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'fhfghfghfghfgh',
                'attachment_url' => NULL,
                'appointment_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-09 13:35:43',
                'updated_at' => '2023-08-17 12:38:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-16T08:59:00.000Z',
                'start_time' => '05:21 PM',
                'end_time' => '05:22 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'dsfsfdsfdsfdsfdssfsd',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-15 12:08:47',
                'updated_at' => '2023-08-15 12:34:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-15T14:41:31.115Z',
                'start_time' => '03:44 PM',
                'end_time' => '03:53 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'refergdfg',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-15 17:42:37',
                'updated_at' => '2023-08-15 17:43:10',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-17T09:07:46.552Z',
                'start_time' => '03:21 PM',
                'end_time' => '03:40 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'hello',
                'attachment_url' => NULL,
                'appointment_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-17 12:08:36',
                'updated_at' => '2023-08-17 12:37:39',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-18T10:42:00.000Z',
                'start_time' => '03:41 PM',
                'end_time' => '04:00 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'hi m',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-17 13:46:07',
                'updated_at' => '2023-08-17 13:53:04',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-22T15:04:27.707Z',
                'start_time' => '03:41 PM',
                'end_time' => '04:00 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'kjkkkk',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-22 18:04:49',
                'updated_at' => '2023-08-22 18:05:08',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'customer_id' => 6,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-25T10:59:31.820Z',
                'start_time' => '04:21 PM',
                'end_time' => '04:40 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'sdfsdfsdf',
                'attachment_url' => NULL,
                'appointment_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-25 13:59:54',
                'updated_at' => '2023-08-29 16:47:08',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-29T12:31:33.358Z',
                'start_time' => '03:54 PM',
                'end_time' => '04:03 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => '29-05-232',
                'attachment_url' => NULL,
                'appointment_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-29 15:34:17',
                'updated_at' => '2023-08-29 15:40:08',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'customer_id' => 1,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-29T13:46:49.044Z',
                'start_time' => '03:34 PM',
                'end_time' => '03:43 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'fghfghfghfgh',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-29 16:48:16',
                'updated_at' => '2023-08-29 16:48:16',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-29T14:13:12.881Z',
                'start_time' => '03:24 PM',
                'end_time' => '03:33 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'Question Question Question Question',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-29 17:14:09',
                'updated_at' => '2023-08-29 17:16:42',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-08-25T09:46:00.000Z',
                'start_time' => '03:21 PM',
                'end_time' => '03:40 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'Ask Your Question',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-08-30 12:51:16',
                'updated_at' => '2023-09-12 16:05:49',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-15T10:57:00.000Z',
                'start_time' => '03:44 PM',
                'end_time' => '03:53 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'dsfdsfds',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-01 13:59:02',
                'updated_at' => '2023-09-12 17:57:01',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-02T16:35:17.715Z',
                'start_time' => '03:44 PM',
                'end_time' => '03:53 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'Vzvsbbsbsbvs',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-02 19:38:39',
                'updated_at' => '2023-09-06 17:52:15',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'customer_id' => 4,
                'lawyer_id' => 1,
                'law_firm_id' => NULL,
                'date' => '2023-09-02T16:35:17.715Z',
                'start_time' => '03:44 PM',
                'end_time' => '03:53 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'asdjklghjghj',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-02 19:38:39',
                'updated_at' => '2023-09-12 12:41:59',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'customer_id' => 4,
                'lawyer_id' => 2,
                'law_firm_id' => NULL,
                'date' => '2023-09-02T16:35:17.715Z',
                'start_time' => '03:44 PM',
                'end_time' => '03:53 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'Need Some Tea',
                'attachment_url' => NULL,
                'appointment_status_code' => 4,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-02 19:38:39',
                'updated_at' => '2023-09-02 19:38:39',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-07T14:19:05.021Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 2,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'hey this is testing',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-07 17:19:42',
                'updated_at' => '2023-09-07 17:20:17',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-08T13:41:04.912Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 2,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'Need Some Help',
                'attachment_url' => '/files/booked_appointments/1694180516Analytics.png',
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-08 16:42:14',
                'updated_at' => '2023-09-08 16:52:17',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-08T14:19:21.345Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 2,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'Hi there',
                'attachment_url' => '/files/booked_appointments/1694182823D05F9039-D132-41A2-AAF2-7E72ED5AB086.png',
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-08 17:20:27',
                'updated_at' => '2023-09-12 19:48:37',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-12T13:10:12.105Z',
                'start_time' => '05:21 PM',
                'end_time' => '05:22 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'new toeday',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-12 16:10:41',
                'updated_at' => '2023-09-12 16:37:35',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-13T13:43:00.000Z',
                'start_time' => '05:21 PM',
                'end_time' => '05:22 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'now todau',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-12 16:44:12',
                'updated_at' => '2023-09-12 16:44:43',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21T14:58:00.000Z',
                'start_time' => '05:21 PM',
                'end_time' => '05:22 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'new todauyfififf',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-12 17:58:37',
                'updated_at' => '2023-09-12 17:59:15',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-12T16:51:04.649Z',
                'start_time' => '03:34 PM',
                'end_time' => '03:43 PM',
                'fee' => 5,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'jihuhiui',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-12 19:51:20',
                'updated_at' => '2023-09-12 19:51:59',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 21:51:23.996486',
                'start_time' => '03:21 PM',
                'end_time' => '03:40 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'Testing',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 19:52:30',
                'updated_at' => '2023-09-18 19:52:30',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:03:48.666960',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok check',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:04:34',
                'updated_at' => '2023-09-18 20:04:34',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:03:48.666960',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok check',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:05:51',
                'updated_at' => '2023-09-18 20:05:51',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:03:48.666960',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok check',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:10:50',
                'updated_at' => '2023-09-18 20:10:50',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:03:48.666960',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok check',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:16:08',
                'updated_at' => '2023-09-18 20:16:08',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:18:35.782684',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'thk',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:19:06',
                'updated_at' => '2023-09-18 20:19:06',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-18 22:18:35.782684',
                'start_time' => '05:01',
                'end_time' => '05:25',
                'fee' => 350,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'thk',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-18 20:19:35',
                'updated_at' => '2023-09-18 20:19:35',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'customer_id' => 5,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19T16:24:29.706Z',
                'start_time' => '17:13',
                'end_time' => '17:46',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'frertertrt',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:24:49',
                'updated_at' => '2023-09-19 19:24:49',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19 21:26:11.610755',
                'start_time' => '16:39',
                'end_time' => '17:12',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:27:26',
                'updated_at' => '2023-09-19 19:27:26',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19 21:26:11.610755',
                'start_time' => '16:39',
                'end_time' => '17:12',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:30:19',
                'updated_at' => '2023-09-19 19:30:19',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19 21:43:41.960460',
                'start_time' => '16:39',
                'end_time' => '17:12',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:44:19',
                'updated_at' => '2023-09-19 19:44:19',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19 21:43:41.960460',
                'start_time' => '16:39',
                'end_time' => '17:12',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:45:08',
                'updated_at' => '2023-09-19 19:45:08',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-19 21:43:41.960460',
                'start_time' => '16:39',
                'end_time' => '17:12',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-19 19:45:57',
                'updated_at' => '2023-09-19 19:45:57',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21 00:00:00.000',
                'start_time' => '09:01',
                'end_time' => '09:03',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 10:22:40',
                'updated_at' => '2023-09-21 10:22:40',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21 12:38:37.647354',
                'start_time' => '09:01',
                'end_time' => '09:03',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 10:39:49',
                'updated_at' => '2023-09-21 10:39:49',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21 12:38:37.647354',
                'start_time' => '09:01',
                'end_time' => '09:03',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 10:43:59',
                'updated_at' => '2023-09-21 10:43:59',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21 12:46:00.658959',
                'start_time' => '09:01',
                'end_time' => '09:03',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 10:47:28',
                'updated_at' => '2023-09-21 10:47:28',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21 12:46:00.658959',
                'start_time' => '09:01',
                'end_time' => '09:03',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 10:55:00',
                'updated_at' => '2023-09-30 22:55:04',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-21T07:59:00.000Z',
                'start_time' => '11:16',
                'end_time' => '11:18',
                'fee' => 23,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => '12345',
                'attachment_url' => '/files/booked_appointments/1695283295jummah mubarak.jpg',
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-21 11:01:36',
                'updated_at' => '2023-09-21 11:02:27',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'customer_id' => 8,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-27 00:00:00.000',
                'start_time' => '18:14',
                'end_time' => '18:43',
                'fee' => 20,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'hi',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-27 16:02:53',
                'updated_at' => '2023-09-27 16:07:34',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-27 19:29:03.266038',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 9,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'Chat Quest',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => '2023-09-27 19:00:34',
                'ended_at' => NULL,
                'created_at' => '2023-09-27 17:47:24',
                'updated_at' => '2023-09-27 19:00:34',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-09-30 19:38:29.340553',
                'start_time' => '20:01',
                'end_time' => '20:30',
                'fee' => 20,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'ok',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-09-30 18:04:40',
                'updated_at' => '2023-09-30 18:05:18',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'customer_id' => 4,
                'lawyer_id' => 15,
                'law_firm_id' => NULL,
                'date' => '2023-10-04 15:58:17.866649',
                'start_time' => '18:14',
                'end_time' => '18:43',
                'fee' => 20,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'hello',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-04 15:59:40',
                'updated_at' => '2023-10-04 15:59:40',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'customer_id' => 4,
                'lawyer_id' => 31,
                'law_firm_id' => NULL,
                'date' => '2023-10-12T08:32:54.239Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 2,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                'attachment_url' => '/files/booked_appointments/1697099617Static-and-dynamic-Website.png',
                'appointment_status_code' => 5,
                'started_at' => '2023-10-12 13:38:04',
                'ended_at' => '2023-10-12 13:41:24',
                'created_at' => '2023-10-12 13:33:38',
                'updated_at' => '2023-10-12 13:41:24',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'customer_id' => 4,
                'lawyer_id' => 30,
                'law_firm_id' => NULL,
                'date' => '2023-10-19T08:27:02.972Z',
                'start_time' => '03:08 PM',
                'end_time' => '03:17 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'Hello',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-19 13:30:19',
                'updated_at' => '2023-10-19 13:30:19',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'customer_id' => 2,
                'lawyer_id' => 14,
                'law_firm_id' => NULL,
                'date' => '2023-10-19T08:36:37.460Z',
                'start_time' => '04:33 PM',
                'end_time' => '04:42 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar ipsum a velit luctus, vitae vulputate enim congue. Phasellus commodo leo et nisl consectetur, in',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-19 13:39:41',
                'updated_at' => '2023-10-19 13:39:41',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'customer_id' => 2,
                'lawyer_id' => 27,
                'law_firm_id' => NULL,
                'date' => '2023-10-19T09:46:42.334Z',
                'start_time' => '03:43 PM',
                'end_time' => '03:52 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 2,
                'question' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-19 14:48:39',
                'updated_at' => '2023-10-31 18:50:07',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'customer_id' => 5,
                'lawyer_id' => 30,
                'law_firm_id' => NULL,
                'date' => '2023-10-19 17:58:31.040894',
                'start_time' => '03:08 PM',
                'end_time' => '03:17 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'hello',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-19 17:59:30',
                'updated_at' => '2023-10-19 17:59:30',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'customer_id' => 4,
                'lawyer_id' => 32,
                'law_firm_id' => NULL,
                'date' => '2023-10-23 16:04:44.301909',
                'start_time' => '02:51 PM',
                'end_time' => '03:10 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'Hey Jimmy',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-23 16:09:27',
                'updated_at' => '2023-10-23 16:09:27',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'customer_id' => 4,
                'lawyer_id' => 33,
                'law_firm_id' => NULL,
                'date' => '2023-10-23 17:59:32.337810',
                'start_time' => '02:51 PM',
                'end_time' => '03:00 PM',
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 1,
                'question' => 'lourm Ipsum dollar site emit',
                'attachment_url' => NULL,
                'appointment_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-23 18:00:24',
                'updated_at' => '2023-10-23 19:05:37',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'customer_id' => 2,
                'lawyer_id' => NULL,
                'law_firm_id' => 3,
                'date' => '2023-10-31T12:09:43.498Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'fsdf asef asdf sdf asef sdaf asdfasdfasdf as fsdfsdf',
                'attachment_url' => NULL,
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-10-31 17:10:21',
                'updated_at' => '2023-10-31 17:10:21',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'customer_id' => 1,
                'lawyer_id' => 33,
                'law_firm_id' => NULL,
                'date' => '2023-11-03T10:36:50.240Z',
                'start_time' => NULL,
                'end_time' => NULL,
                'fee' => 10,
                'is_paid' => 1,
                'appointment_type_id' => 3,
                'question' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                'attachment_url' => '/files/booked_appointments/1699007878low-angle-coworkers-meeting-discussions_23-2148339349.avif',
                'appointment_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2023-11-03 15:37:59',
                'updated_at' => '2023-11-03 15:37:59',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}