<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GatewaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('gateways')->delete();
        
        \DB::table('gateways')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Paypal',
                'code' => 'paypal',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"cleint_id":"asdasd93485","secret":"upadasdml234"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.01200000',
                'currencies' => '{"0":{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"USD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '1.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770081paypal.png',
                'sort_by' => 14,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:28:01',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Stripe ',
                'code' => 'stripe',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"secret_key":"sk_test_4mIgs731P1pD8aEEO57Ytf5v","publishable_key":"pk_test_0OgQlXP7CRZ0AzpdcYQfM496","endpoint_secret":"sdfsdfdsfdfssdf"}',
                'extra_parameters' => '{"webhook":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770267stripe.png',
                'sort_by' => 23,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:31:07',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Skrill',
                'code' => 'skrill',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"pay_to_email":"sds","secret_key":"wewedr"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BHD":"BHD","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","INR":"INR","ISK":"ISK","JOD":"JOD","JPY":"JPY","KRW":"KRW","KWD":"KWD","MAD":"MAD","MYR":"MYR","NOK":"NOK","NZD":"NZD","OMR":"OMR","PLN":"PLN","QAR":"QAR","RON":"RON","RSD":"RSD","SAR":"SAR","SEK":"SEK","SGD":"SGD","THB":"THB","TND":"TND","TRY":"TRY","TWD":"TWD","USD":"USD","ZAR":"ZAR","COP":"COP"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770231skrill.png',
                'sort_by' => 22,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:30:31',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Perfect Money',
                'code' => 'perfectmoney',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"passphrase":"sdsd","payee_account":"sdwe"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770189perfect-money.png',
                'sort_by' => 18,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:29:49',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'PayTM',
                'code' => 'paytm',
                'currency' => 'INR',
                'symbol' => 'INR',
                'parameters' => '{"MID":"sdsd","merchant_key":"sdsd","WEBSITE":"sds","INDUSTRY_TYPE_ID":"wewe","CHANNEL_ID":"fwd","environment_url":"weecf","process_transaction_url":"sdsd"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AUD":"AUD","ARS":"ARS","BDT":"BDT","BRL":"BRL","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","HRK":"HRK","CZK":"CZK","DKK":"DKK","EGP":"EGP","EUR":"EUR","GEL":"GEL","GHS":"GHS","HKD":"HKD","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JPY":"JPY","KES":"KES","MYR":"MYR","MXN":"MXN","MAD":"MAD","NPR":"NPR","NZD":"NZD","NGN":"NGN","NOK":"NOK","PKR":"PKR","PEN":"PEN","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SGD":"SGD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","THB":"THB","TRY":"TRY","UGX":"UGX","UAH":"UAH","AED":"AED","GBP":"GBP","USD":"USD","VND":"VND","XOF":"XOF"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770131payTM.png',
                'sort_by' => 16,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:28:51',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Payeer',
                'code' => 'payeer',
                'currency' => 'RUB',
                'symbol' => 'USD',
                'parameters' => '{"merchant_id":"P1109116078","secret_key":"m5R81LJ7Ieu33h8Y"}',
                'extra_parameters' => '{"status":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR","RUB":"RUB"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770067payeer.png',
                'sort_by' => 13,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-29 11:45:54',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'PayStack',
                'code' => 'paystack',
                'currency' => 'NGN',
                'symbol' => 'NGN',
                'parameters' => '{"public_key":"sdsd","secret_key":"sdsdsd"}',
                'extra_parameters' => '{"callback":"ipn","webhook":"ipn"}
',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD","NGN":"NGN"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770094paystack.png',
                'sort_by' => 15,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:28:14',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'VoguePay',
                'code' => 'voguepay',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"merchant_id":"dsferweds"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"NGN":"NGN","USD":"USD","EUR":"EUR","GBP":"GBP","ZAR":"ZAR","JPY":"JPY","INR":"INR","AUD":"AUD","CAD":"CAD","NZD":"NZD","NOK":"NOK","PLN":"PLN"}}








',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770276VoguePay .png',
                'sort_by' => 21,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:31:16',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Flutterwave',
                'code' => 'flutterwave',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"public_key":"erer","secret_key":"erer","encryption_key":"ererer"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.01200000',
                'currencies' => '{"0":{"KES":"KES","GHS":"GHS","NGN":"NGN","USD":"USD","GBP":"GBP","EUR":"EUR","UGX":"UGX","TZS":"TZS"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703769941Flutterwave.png',
                'sort_by' => 8,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:25:41',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'RazorPay',
                'code' => 'razorpay',
                'currency' => 'INR',
                'symbol' => 'INR',
                'parameters' => '{"key_id":"rzp_test_LbK7OKIrPbCFo3","key_secret":"j7Gjtvc6zr4eFkUTqfpuAZVd"}',
                'extra_parameters' => NULL,
                'convention_rate' => '10.00000000',
                'currencies' => '{"0": {"INR": "INR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770202razorpay.png',
                'sort_by' => 19,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2024-01-12 07:31:08',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'instamojo',
                'code' => 'instamojo',
                'currency' => 'INR',
                'symbol' => 'INR',
                'parameters' => '{"api_key":"weeee","auth_token":"dfvfdg","salt":"gdfgffgdgdf"}',
                'extra_parameters' => NULL,
                'convention_rate' => '73.51000000',
                'currencies' => '{"0":{"INR":"INR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703769970instamojo.png',
                'sort_by' => 9,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:26:10',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Mollie',
                'code' => 'mollie',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"api_key":"dsdsdds"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.01200000',
                'currencies' => '{"0":{"AED":"AED","AUD":"AUD","BGN":"BGN","BRL":"BRL","CAD":"CAD","CHF":"CHF","CZK":"CZK","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","HRK":"HRK","HUF":"HUF","ILS":"ILS","ISK":"ISK","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD","USD":"USD","ZAR":"ZAR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770011mollie.png',
                'sort_by' => 11,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:26:51',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '2checkout',
                'code' => 'twocheckout',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"merchant_code":"df","secret_key":"dfdf"}',
                'extra_parameters' => '{"approved_url":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AFN":"AFN","ALL":"ALL","DZD":"DZD","ARS":"ARS","AUD":"AUD","AZN":"AZN","BSD":"BSD","BDT":"BDT","BBD":"BBD","BZD":"BZD","BMD":"BMD","BOB":"BOB","BWP":"BWP","BRL":"BRL","GBP":"GBP","BND":"BND","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","HRK":"HRK","CZK":"CZK","DKK":"DKK","DOP":"DOP","XCD":"XCD","EGP":"EGP","EUR":"EUR","FJD":"FJD","GTQ":"GTQ","HKD":"HKD","HNL":"HNL","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JMD":"JMD","JPY":"JPY","KZT":"KZT","KES":"KES","LAK":"LAK","MMK":"MMK","LBP":"LBP","LRD":"LRD","MOP":"MOP","MYR":"MYR","MVR":"MVR","MRO":"MRO","MUR":"MUR","MXN":"MXN","MAD":"MAD","NPR":"NPR","TWD":"TWD","NZD":"NZD","NIO":"NIO","NOK":"NOK","PKR":"PKR","PGK":"PGK","PEN":"PEN","PHP":"PHP","PLN":"PLN","QAR":"QAR","RON":"RON","RUB":"RUB","WST":"WST","SAR":"SAR","SCR":"SCR","SGD":"SGD","SBD":"SBD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","SYP":"SYP","THB":"THB","TOP":"TOP","TTD":"TTD","TRY":"TRY","UAH":"UAH","AED":"AED","USD":"USD","VUV":"VUV","VND":"VND","XOF":"XOF","YER":"YER"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/17037698362checkout.png',
                'sort_by' => 24,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:23:56',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Authorize.Net',
                'code' => 'authorizenet',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"login_id":"gfghhggh","current_transaction_key":"hghfghfghg"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.01200000',
                'currencies' => '{"0":{"AUD":"AUD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","USD":"USD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703769862Authorize-net.png',
                'sort_by' => 1,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:24:22',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'SecurionPay',
                'code' => 'securionpay',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"public_key":"sddssd","secret_key":"wewewef"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AFN":"AFN", "DZD":"DZD", "ARS":"ARS", "AUD":"AUD", "BHD":"BHD", "BDT":"BDT", "BYR":"BYR", "BAM":"BAM", "BWP":"BWP", "BRL":"BRL", "BND":"BND", "BGN":"BGN", "CAD":"CAD", "CLP":"CLP", "CNY":"CNY", "COP":"COP", "KMF":"KMF", "HRK":"HRK", "CZK":"CZK", "DKK":"DKK", "DJF":"DJF", "DOP":"DOP", "EGP":"EGP", "ETB":"ETB", "ERN":"ERN", "EUR":"EUR", "GEL":"GEL", "HKD":"HKD", "HUF":"HUF", "ISK":"ISK", "INR":"INR", "IDR":"IDR", "IRR":"IRR", "IQD":"IQD", "ILS":"ILS", "JMD":"JMD", "JPY":"JPY", "JOD":"JOD", "KZT":"KZT", "KES":"KES", "KWD":"KWD", "KGS":"KGS", "LVL":"LVL", "LBP":"LBP", "LTL":"LTL", "MOP":"MOP", "MKD":"MKD", "MGA":"MGA", "MWK":"MWK", "MYR":"MYR", "MUR":"MUR", "MXN":"MXN", "MDL":"MDL", "MAD":"MAD", "MZN":"MZN", "NAD":"NAD", "NPR":"NPR", "ANG":"ANG", "NZD":"NZD", "NOK":"NOK", "OMR":"OMR", "PKR":"PKR", "PEN":"PEN", "PHP":"PHP", "PLN":"PLN", "QAR":"QAR", "RON":"RON", "RUB":"RUB", "SAR":"SAR", "RSD":"RSD", "SGD":"SGD", "ZAR":"ZAR", "KRW":"KRW", "IKR":"IKR", "LKR":"LKR", "SEK":"SEK", "CHF":"CHF", "SYP":"SYP", "TWD":"TWD", "TZS":"TZS", "THB":"THB", "TND":"TND", "TRY":"TRY", "UAH":"UAH", "AED":"AED", "GBP":"GBP", "USD":"USD", "VEB":"VEB", "VEF":"VEF", "VND":"VND", "XOF":"XOF", "YER":"YER", "ZMK":"ZMK"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770213Securionpay.png',
                'sort_by' => 20,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:30:13',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'PayUmoney',
                'code' => 'payumoney',
                'currency' => 'INR',
                'symbol' => 'INR',
                'parameters' => '{"merchant_key":"dsfd","salt":"sdfsdf"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.87000000',
                'currencies' => '{"0":{"INR":"INR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770174payumoney.png',
                'sort_by' => 17,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:29:34',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Mercado Pago',
                'code' => 'mercadopago',
                'currency' => 'BRL',
                'symbol' => 'BRL',
                'parameters' => '{"access_token":"sdfdsf"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.06300000',
                'currencies' => '{"0":{"ARS":"ARS","BOB":"BOB","BRL":"BRL","CLF":"CLF","CLP":"CLP","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","DOP":"DOP","EUR":"EUR","GTQ":"GTQ","HNL":"HNL","MXN":"MXN","NIO":"NIO","PAB":"PAB","PEN":"PEN","PYG":"PYG","USD":"USD","UYU":"UYU","VEF":"VEF","VES":"VES"}}',
                'min_amount' => '3715.12000000',
                'max_amount' => '371500000.12000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770000mercado-pago.png',
                'sort_by' => 10,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:26:40',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Coingate',
                'code' => 'coingate',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"api_key":"eeee"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD","EUR":"EUR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703769910Coingate.png',
                'sort_by' => 7,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:25:10',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Coinbase Commerce',
                'code' => 'coinbasecommerce',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"api_key":"ghf","secret":"fhg"}',
                'extra_parameters' => '{"webhook":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AED":"AED","AFN":"AFN","ALL":"ALL","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZN":"AZN","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYN":"BYN","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLF":"CLF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","CVE":"CVE","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHS":"GHS","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZN":"MZN","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PYG":"PYG","QAR":"QAR","RON":"RON","RSD":"RSD","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDG":"SDG","SEK":"SEK","SGD":"SGD","SHP":"SHP","SLL":"SLL","SOS":"SOS","SRD":"SRD","SSP":"SSP","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMT":"TMT","TND":"TND","TOP":"TOP","TRY":"TRY","TTD":"TTD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMW":"ZMW","ZWL":"ZWL"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703769893coinbase-commerce.png',
                'sort_by' => 3,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:24:53',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Monnify',
                'code' => 'monnify',
                'currency' => 'NGN',
                'symbol' => 'NGN',
                'parameters' => '{"api_key":"sdsd","secret_key":"sdsd","contract_code":"ffeffdfs"}',
                'extra_parameters' => NULL,
                'convention_rate' => '4.52000000',
                'currencies' => '{"0":{"NGN":"NGN"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '/files/payment_gateways/1703770029monnify.png',
                'sort_by' => 12,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 13:27:09',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Block.io',
                'code' => 'blockio',
                'currency' => 'BTC',
                'symbol' => 'BTC',
                'parameters' => '{"api_key":"1e83-f033-177a-1644","api_pin":"A62C503A6032C8C3"}',
                'extra_parameters' => '{"cron":"ipn"}',
                'convention_rate' => '0.00004200',
                'currencies' => '{"1":{"BTC":"BTC","LTC":"LTC","DOGE":"DOGE"}}',
                'min_amount' => '10.10000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '5fe038332ad52.jpg',
                'sort_by' => 2,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 14:05:07',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'CoinPayments',
                'code' => 'coinpayments',
                'currency' => 'BTC',
                'symbol' => 'BTC',
                'parameters' => '{"merchant_id":"86ebca4746ea46796e58538f0e6e34f6","private_key":"e177C49cc9bBb93b94A83f74229Acf6507E77d955Ba8ac0E742C71d3EC70fc6b","public_key":"c8d66aa5e9eeeaffb6c0e9cfa00108d9743bed570523d43e7fe8237841dd1be6"}',
                'extra_parameters' => '{"callback":"ipn"}',
                'convention_rate' => '0.00000000',
            'currencies' => '{"0":{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","ISK":"ISK","JPY":"JPY","KRW":"KRW","NZD":"NZD","PLN":"PLN","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD"},"1":{"BTC":"Bitcoin","BTC.LN":"Bitcoin (Lightning Network)","LTC":"Litecoin","CPS":"CPS Coin","VLX":"Velas","APL":"Apollo","AYA":"Aryacoin","BAD":"Badcoin","BCD":"Bitcoin Diamond","BCH":"Bitcoin Cash","BCN":"Bytecoin","BEAM":"BEAM","BITB":"Bean Cash","BLK":"BlackCoin","BSV":"Bitcoin SV","BTAD":"Bitcoin Adult","BTG":"Bitcoin Gold","BTT":"BitTorrent","CLOAK":"CloakCoin","CLUB":"ClubCoin","CRW":"Crown","CRYP":"CrypticCoin","CRYT":"CryTrExCoin","CURE":"CureCoin","DASH":"DASH","DCR":"Decred","DEV":"DeviantCoin","DGB":"DigiByte","DOGE":"Dogecoin","EBST":"eBoost","EOS":"EOS","ETC":"Ether Classic","ETH":"Ethereum","ETN":"Electroneum","EUNO":"EUNO","EXP":"EXP","Expanse":"Expanse","FLASH":"FLASH","GAME":"GameCredits","GLC":"Goldcoin","GRS":"Groestlcoin","KMD":"Komodo","LOKI":"LOKI","LSK":"LSK","MAID":"MaidSafeCoin","MUE":"MonetaryUnit","NAV":"NAV Coin","NEO":"NEO","NMC":"Namecoin","NVST":"NVO Token","NXT":"NXT","OMNI":"OMNI","PINK":"PinkCoin","PIVX":"PIVX","POT":"PotCoin","PPC":"Peercoin","PROC":"ProCurrency","PURA":"PURA","QTUM":"QTUM","RES":"Resistance","RVN":"Ravencoin","RVR":"RevolutionVR","SBD":"Steem Dollars","SMART":"SmartCash","SOXAX":"SOXAX","STEEM":"STEEM","STRAT":"STRAT","SYS":"Syscoin","TPAY":"TokenPay","TRIGGERS":"Triggers","TRX":" TRON","UBQ":"Ubiq","UNIT":"UniversalCurrency","USDT":"Tether USD (Omni Layer)","VTC":"Vertcoin","WAVES":"Waves","XCP":"Counterparty","XEM":"NEM","XMR":"Monero","XSN":"Stakenet","XSR":"SucreCoin","XVG":"VERGE","XZC":"ZCoin","ZEC":"ZCash","ZEN":"Horizen"}}',
                'min_amount' => '10.00000000',
                'max_amount' => '99999.00000000',
                'percentage_charge' => '1.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '5ffd7d962985e1610448278.jpg',
                'sort_by' => 6,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 14:28:50',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Blockchain',
                'code' => 'blockchain',
                'currency' => 'BTC',
                'symbol' => 'BTC',
                'parameters' => '{"api_key":"a82a8a6a-6411-452f-9741-d4ec46e541e6","xpub_code":"xpub6Cq2NpFqoqX5DRsyhebKRH2fCsBUneBpBHXyz5mZAZojesJguZJnBpG6MFGdkio1oTd3GrXoCi9HDFTC5xZoSZN7KZUpn24bPdh5dqyrkYK"}',
                'extra_parameters' => NULL,
                'convention_rate' => '0.00000000',
                'currencies' => '{"1":{"BTC":"BTC"}}',
                'min_amount' => '100.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '5fe439f477bb7.jpg',
                'sort_by' => 4,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-29 07:49:14',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Midtrans',
                'code' => 'midtrans',
                'currency' => 'IDR',
                'symbol' => 'IDR',
                'parameters' => '{"client_key":"","server_key":""}',
                'extra_parameters' => '{"payment_notification_url":"ipn", "finish redirect_url":"ipn", "unfinish redirect_url":"failed","error redirect_url":"failed"}',
                'convention_rate' => '15116.00000000',
                'currencies' => '{"0":{"IDR":"IDR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '1000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e346c234f5e1675839170.png',
                'sort_by' => 1,
                'created_at' => '2023-02-08 11:17:49',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'cashmaal',
                'code' => 'cashmaal',
                'currency' => 'PKR',
                'symbol' => 'PKR',
                'parameters' => '{"web_id":"9596","ipn_key":"dzgPkLJCBcYW4Q3be2yOl5ot5ApGnqXIxdw"}',
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'convention_rate' => '0.85000000',
                'currencies' => '{"0":{"PKR":"PKR","USD":"USD"}}',
                'min_amount' => '2.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => 'cashmaal.jpg',
                'sort_by' => 5,
                'created_at' => '2020-09-10 14:05:02',
                'updated_at' => '2023-12-28 14:49:29',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'peachpayments',
                'code' => 'peachpayments',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"Authorization_Bearer":"df","Entity_ID":"df","Recur_Channel":"fd"}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"AED":"AED","AFA":"AFA","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AUD":"AUD","AWG":"AWG","AZM":"AZM","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BRL":"BRL","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYR":"BYR","BZD":"BZD","CAD":"CAD","CDF":"CDF","CHF":"CHF","CLP":"CLP","CNY":"CNY","COP":"COP","CRC":"CRC","CUP":"CUP","CVE":"CVE","CYP":"CYP","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EEK":"EEK","EGP":"EGP","ERN":"ERN","ETB":"ETB","EUR":"EUR","FJD":"FJD","FKP":"FKP","GBP":"GBP","GEL":"GEL","GGP":"GGP","GHC":"GHC","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HKD":"HKD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","INR":"INR","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","JPY":"JPY","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KRW":"KRW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LTL":"LTL","LVL":"LVL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MTL":"MTL","MUR":"MUR","MVR":"MVR","MWK":"MWK","MXN":"MXN","MYR":"MYR","MZM":"MZM","NAD":"NAD","NGN":"NGN","NIO":"NIO","NOK":"NOK","NPR":"NPR","NZD":"NZD","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PTS":"PTS","PYG":"PYG","QAR":"QAR","RON":"RON","RUB":"RUB","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDD":"SDD","SEK":"SEK","SGD":"SGD","SHP":"SHP","SIT":"SIT","SKK":"SKK","SLL":"SLL","SOS":"SOS","SPL":"SPL","SRD":"SRD","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMM":"TMM","TND":"TND","TOP":"TOP","TRL":"TRL","TRY":"TRY","TTD":"TTD","TVD":"TVD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","USD":"USD","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZAR":"ZAR","ZMK":"ZMK","ZWD":"ZWD"}}',
                'min_amount' => '100.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '63e0b543ef3461675670851.png',
                'sort_by' => 11,
                'created_at' => '2020-09-10 08:05:02',
                'updated_at' => '2023-12-28 11:38:30',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Nowpayments',
                'code' => 'nowpayments',
                'currency' => 'BTC',
                'symbol' => 'BTC',
                'parameters' => '{"api_key":""}',
                'extra_parameters' => '{"cron":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"1":{"BTC":"BTC","LTC":"LTC","DOGE":"DOGE"}}',
                'min_amount' => '10.10000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.50000000',
                'status' => 1,
                'note' => '',
                'image' => '63e0b44aa1dac1675670602.jpg',
                'sort_by' => 7,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Khalti Payment',
                'code' => 'khalti',
                'currency' => 'NPR',
                'symbol' => 'NPR',
                'parameters' => '{"secret_key":"","public_key":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '132.04000000',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'min_amount' => '100.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e0b4a473d5b1675670692.webp',
                'sort_by' => 9,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'MAGUA PAY',
                'code' => 'swagger',
                'currency' => 'EUR',
                'symbol' => 'EUR',
                'parameters' => '{"MAGUA_PAY_ACCOUNT":"","MerchantKey":"","Secret":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"EUR":"EUR"}}',
                'min_amount' => '100.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '64017cd2019331677819090.jpg',
                'sort_by' => 8,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Free kassa',
                'code' => 'freekassa',
                'currency' => 'RUB',
                'symbol' => 'RUB',
                'parameters' => '{"merchant_id":"","merchant_key":"","secret_word":"","secret_word2":""}',
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"RUB":"RUB","USD":"USD","EUR":"EUR","UAH":"UAH","KZT":"KZT"}}',
                'min_amount' => '10.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.1000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e0b428d97d11675670568.jpg',
                'sort_by' => 5,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Konnect',
                'code' => 'konnect',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"api_key":"","receiver_wallet_Id":""}',
                'extra_parameters' => '{"webhook":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"TND":"TND","EUR":"EUR","USD":"USD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '10000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e0b3deb4a7d1675670494.jpg',
                'sort_by' => 4,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Mypay Np',
                'code' => 'mypay',
                'currency' => 'NPR',
                'symbol' => 'NPR',
                'parameters' => '{"merchant_username":"","merchant_api_password":"","merchant_id":"","api_key":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '100000.00000000',
                'percentage_charge' => '1.5000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e34b53a962a1675840339.png',
                'sort_by' => 10,
                'created_at' => '2020-09-10 02:05:02',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'PayThrow',
                'code' => 'paythrow',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"client_id":"","client_secret":""}',
                'extra_parameters' => '{"ipn_url":"ipn"}',
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"PKR":"PKR","USD":"USD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '1000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e3471f5f6de1675839263.jpg',
                'sort_by' => 1,
                'created_at' => '2023-02-08 11:17:24',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'IME PAY',
                'code' => 'imepay',
                'currency' => 'NPR',
                'symbol' => 'NPR',
                'parameters' => '{"MerchantModule":"","MerchantCode":"","username":"","password":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"NPR":"NPR"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '1000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e348c93b8ce1675839689.png',
                'sort_by' => 1,
                'created_at' => '2023-02-08 11:17:49',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Binance',
                'code' => 'binance',
                'currency' => 'USDT',
                'symbol' => 'USDT',
                'parameters' => '{"mercent_api_key":"","mercent_secret":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"1":{"ADA":"ADA","ATOM":"ATOM","AVA":"AVA","BCH":"BCH","BNB":"BNB","BTC":"BTC","BUSD":"BUSD","CTSI":"CTSI","DASH":"DASH","DOGE":"DOGE","DOT":"DOT","EGLD":"EGLD","EOS":"EOS","ETC":"ETC","ETH":"ETH","FIL":"FIL","FRONT":"FRONT","FTM":"FTM","GRS":"GRS","HBAR":"HBAR","IOTX":"IOTX","LINK":"LINK","LTC":"LTC","MANA":"MANA","MATIC":"MATIC","NEO":"NEO","OM":"OM","ONE":"ONE","PAX":"PAX","QTUM":"QTUM","STRAX":"STRAX","SXP":"SXP","TRX":"TRX","TUSD":"TUSD","UNI":"UNI","USDC":"USDC","USDT":"USDT","WRX":"WRX","XLM":"XLM","XMR":"XMR","XRP":"XRP","XTZ":"XTZ","XVS":"XVS","ZEC":"ZEC","ZIL":"ZIL"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '1000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '63e3483776e411675839543.png',
                'sort_by' => 1,
                'created_at' => '2023-02-08 11:17:49',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Cashonex ',
                'code' => 'cashonexHosted',
                'currency' => 'USD',
                'symbol' => 'USD',
                'parameters' => '{"idempotency_key":"","salt":""}',
                'extra_parameters' => NULL,
                'convention_rate' => '1.00000000',
                'currencies' => '{"0":{"USD":"USD"}}',
                'min_amount' => '1.00000000',
                'max_amount' => '1000.00000000',
                'percentage_charge' => '0.0000',
                'fixed_charge' => '0.00000000',
                'status' => 1,
                'note' => '',
                'image' => '64017c5d76cff1677818973.jpg',
                'sort_by' => 1,
                'created_at' => '2023-02-08 11:17:49',
                'updated_at' => '2023-03-03 13:39:25',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}