<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LawFirmSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('law_firm_settings')->delete();
        
        \DB::table('law_firm_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'law_firm_id' => 5,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            1 => 
            array (
                'id' => 2,
                'law_firm_id' => 5,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://twitter.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            2 => 
            array (
                'id' => 3,
                'law_firm_id' => 5,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.youtube.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            3 => 
            array (
                'id' => 4,
                'law_firm_id' => 5,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.tiktok.com/en/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            4 => 
            array (
                'id' => 5,
                'law_firm_id' => 5,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.tiktok.com/en/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            5 => 
            array (
                'id' => 6,
                'law_firm_id' => 5,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://web.whatsapp.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            6 => 
            array (
                'id' => 7,
                'law_firm_id' => 5,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.snapchat.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            7 => 
            array (
                'id' => 8,
                'law_firm_id' => 5,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.instagram.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            8 => 
            array (
                'id' => 9,
                'law_firm_id' => 5,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.pinterest.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:35:06',
                'updated_at' => '2023-10-05 17:35:06',
            ),
            9 => 
            array (
                'id' => 10,
                'law_firm_id' => 5,
                'name' => 'instagram_profile_link',
                'display_name' => 'Instagram Profile Link',
                'value' => 'https://www.instagram.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:56:17',
                'updated_at' => '2023-10-05 17:56:17',
            ),
            10 => 
            array (
                'id' => 11,
                'law_firm_id' => 5,
                'name' => 'instagram_access_token',
                'display_name' => 'Instagram Access Token',
                'value' => 'https://www.instagram.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:56:17',
                'updated_at' => '2023-10-05 17:56:17',
            ),
            11 => 
            array (
                'id' => 12,
                'law_firm_id' => 5,
                'name' => 'youtube_playlist_link',
                'display_name' => 'Youtube PlayList Link',
                'value' => 'https://www.youtube.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:56:21',
                'updated_at' => '2023-10-05 17:56:21',
            ),
            12 => 
            array (
                'id' => 13,
                'law_firm_id' => 5,
                'name' => 'youtube_channel_link',
                'display_name' => 'Youtube Channel Link',
                'value' => 'https://www.youtube.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 17:56:21',
                'updated_at' => '2023-10-05 17:56:21',
            ),
            13 => 
            array (
                'id' => 14,
                'law_firm_id' => 6,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            14 => 
            array (
                'id' => 15,
                'law_firm_id' => 6,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            15 => 
            array (
                'id' => 16,
                'law_firm_id' => 6,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            16 => 
            array (
                'id' => 17,
                'law_firm_id' => 6,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            17 => 
            array (
                'id' => 18,
                'law_firm_id' => 6,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            18 => 
            array (
                'id' => 19,
                'law_firm_id' => 6,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            19 => 
            array (
                'id' => 20,
                'law_firm_id' => 6,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            20 => 
            array (
                'id' => 21,
                'law_firm_id' => 6,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            21 => 
            array (
                'id' => 22,
                'law_firm_id' => 6,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.linkedin.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-05 19:16:03',
                'updated_at' => '2023-10-05 19:16:03',
            ),
            22 => 
            array (
                'id' => 23,
                'law_firm_id' => 3,
                'name' => 'youtube_playlist_link',
                'display_name' => 'Youtube PlayList Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-13 18:40:43',
                'updated_at' => '2023-10-13 18:40:43',
            ),
            23 => 
            array (
                'id' => 24,
                'law_firm_id' => 3,
                'name' => 'youtube_channel_link',
                'display_name' => 'Youtube Channel Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-13 18:40:43',
                'updated_at' => '2023-10-13 18:40:43',
            ),
            24 => 
            array (
                'id' => 25,
                'law_firm_id' => 3,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            25 => 
            array (
                'id' => 26,
                'law_firm_id' => 3,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            26 => 
            array (
                'id' => 27,
                'law_firm_id' => 3,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            27 => 
            array (
                'id' => 28,
                'law_firm_id' => 3,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            28 => 
            array (
                'id' => 29,
                'law_firm_id' => 3,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            29 => 
            array (
                'id' => 30,
                'law_firm_id' => 3,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            30 => 
            array (
                'id' => 31,
                'law_firm_id' => 3,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            31 => 
            array (
                'id' => 32,
                'law_firm_id' => 3,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            32 => 
            array (
                'id' => 33,
                'law_firm_id' => 3,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-16 16:37:16',
                'updated_at' => '2023-10-16 16:37:16',
            ),
            33 => 
            array (
                'id' => 34,
                'law_firm_id' => 1,
                'name' => 'youtube_playlist_link',
                'display_name' => 'Youtube PlayList Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            34 => 
            array (
                'id' => 35,
                'law_firm_id' => 1,
                'name' => 'youtube_channel_link',
                'display_name' => 'Youtube Channel Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            35 => 
            array (
                'id' => 36,
                'law_firm_id' => 1,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            36 => 
            array (
                'id' => 37,
                'law_firm_id' => 1,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            37 => 
            array (
                'id' => 38,
                'law_firm_id' => 1,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            38 => 
            array (
                'id' => 39,
                'law_firm_id' => 1,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            39 => 
            array (
                'id' => 40,
                'law_firm_id' => 1,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            40 => 
            array (
                'id' => 41,
                'law_firm_id' => 1,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            41 => 
            array (
                'id' => 42,
                'law_firm_id' => 1,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            42 => 
            array (
                'id' => 43,
                'law_firm_id' => 1,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            43 => 
            array (
                'id' => 44,
                'law_firm_id' => 1,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            44 => 
            array (
                'id' => 45,
                'law_firm_id' => 5,
                'name' => 'youtube_playlist_link',
                'display_name' => 'Youtube PlayList Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            45 => 
            array (
                'id' => 46,
                'law_firm_id' => 5,
                'name' => 'youtube_channel_link',
                'display_name' => 'Youtube Channel Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            46 => 
            array (
                'id' => 47,
                'law_firm_id' => 5,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            47 => 
            array (
                'id' => 48,
                'law_firm_id' => 5,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            48 => 
            array (
                'id' => 49,
                'law_firm_id' => 5,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            49 => 
            array (
                'id' => 50,
                'law_firm_id' => 5,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            50 => 
            array (
                'id' => 51,
                'law_firm_id' => 5,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            51 => 
            array (
                'id' => 52,
                'law_firm_id' => 5,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            52 => 
            array (
                'id' => 53,
                'law_firm_id' => 5,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            53 => 
            array (
                'id' => 54,
                'law_firm_id' => 5,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            54 => 
            array (
                'id' => 55,
                'law_firm_id' => 5,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            55 => 
            array (
                'id' => 56,
                'law_firm_id' => 6,
                'name' => 'youtube_playlist_link',
                'display_name' => 'Youtube PlayList Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            56 => 
            array (
                'id' => 57,
                'law_firm_id' => 6,
                'name' => 'youtube_channel_link',
                'display_name' => 'Youtube Channel Link',
                'value' => 'https://www.youtube.com/embed/ckAR1v_ZXwk?si=LGRrw8rEtWNJShvl',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            57 => 
            array (
                'id' => 58,
                'law_firm_id' => 6,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            58 => 
            array (
                'id' => 59,
                'law_firm_id' => 6,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            59 => 
            array (
                'id' => 60,
                'law_firm_id' => 6,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            60 => 
            array (
                'id' => 61,
                'law_firm_id' => 6,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            61 => 
            array (
                'id' => 62,
                'law_firm_id' => 6,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            62 => 
            array (
                'id' => 63,
                'law_firm_id' => 6,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            63 => 
            array (
                'id' => 64,
                'law_firm_id' => 6,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            64 => 
            array (
                'id' => 65,
                'law_firm_id' => 6,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
            65 => 
            array (
                'id' => 66,
                'law_firm_id' => 6,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2023-10-17 17:22:43',
                'updated_at' => '2023-10-17 17:22:43',
            ),
        ));
        
        
    }
}