<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LawyerReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lawyer_reviews')->delete();
        
        \DB::table('lawyer_reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'lawyer_id' => 15,
                'customer_id' => 4,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'lawyer_id' => 14,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'lawyer_id' => 13,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'lawyer_id' => 12,
                'customer_id' => 4,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'lawyer_id' => 11,
                'customer_id' => 8,
                'rating' => 4.5,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'lawyer_id' => 15,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'lawyer_id' => 15,
                'customer_id' => 8,
                'rating' => 4.5,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'lawyer_id' => 14,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'lawyer_id' => 14,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-13 20:10:20',
                'updated_at' => '2023-10-13 20:10:20',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'lawyer_id' => 1,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'lawyer_id' => 1,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'lawyer_id' => 1,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'lawyer_id' => 2,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'lawyer_id' => 2,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'lawyer_id' => 2,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'lawyer_id' => 3,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'lawyer_id' => 3,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'lawyer_id' => 3,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'lawyer_id' => 8,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'lawyer_id' => 8,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'lawyer_id' => 8,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'lawyer_id' => 9,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'lawyer_id' => 9,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'lawyer_id' => 9,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'lawyer_id' => 11,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'lawyer_id' => 11,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'lawyer_id' => 11,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'lawyer_id' => 12,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'lawyer_id' => 12,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'lawyer_id' => 12,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'lawyer_id' => 13,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'lawyer_id' => 13,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'lawyer_id' => 13,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'lawyer_id' => 15,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'lawyer_id' => 15,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'lawyer_id' => 15,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'lawyer_id' => 21,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'lawyer_id' => 21,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'lawyer_id' => 21,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'lawyer_id' => 22,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'lawyer_id' => 22,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'lawyer_id' => 22,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'lawyer_id' => 23,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'lawyer_id' => 23,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'lawyer_id' => 23,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'lawyer_id' => 24,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'lawyer_id' => 24,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'lawyer_id' => 24,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'lawyer_id' => 25,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'lawyer_id' => 25,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'lawyer_id' => 25,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'lawyer_id' => 26,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'lawyer_id' => 26,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'lawyer_id' => 26,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'lawyer_id' => 27,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'lawyer_id' => 27,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'lawyer_id' => 27,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'lawyer_id' => 28,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'lawyer_id' => 28,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'lawyer_id' => 28,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'lawyer_id' => 29,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'lawyer_id' => 29,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'lawyer_id' => 29,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'lawyer_id' => 30,
                'customer_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'lawyer_id' => 30,
                'customer_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and customer service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'lawyer_id' => 30,
                'customer_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}