<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Super Admin',
                'email' => 'superadmin@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2022-01-28 15:16:30',
                'password' => '$2y$10$sH.J0GxgRCaTcEhEHzPrnevIbkl9s0fxBe42dIpE2/nDSHUTkQO0e',
                'role_id' => NULL,
            'profile_image_path' => '/profile_images/1690905720download (2).jpeg',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-08-03 11:43:37',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Jack Deen',
                'email' => 'jack@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-01 16:54:49',
                'password' => '$2y$10$pl5t8Z/NHRS3OFgs6IOQyu6aFCYDP66/gUHCnGo4KaE7LAgu6WaRO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-01 16:54:49',
                'updated_at' => '2023-08-01 16:54:49',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'John Doe',
                'email' => 'john@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-03 15:45:50',
                'password' => '$2y$10$7Cf/DNx3d2xlgBPVXC2Z9.33L4jv0XKBfETYpfiRbwNx.QbrIzhiO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-03 15:45:50',
                'updated_at' => '2023-08-03 15:45:50',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Ahsan Mono',
                'email' => 'ahsan.mono@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-03 15:51:33',
                'password' => '$2y$10$veRZAJvI0xmMXiUhA2LIlevByepZFlOVBjK2jAAPgKXZ4Gf0tbWyu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-03 15:51:33',
                'updated_at' => '2023-08-03 15:51:33',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Ana mark',
                'email' => 'anamark@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-04 13:47:33',
                'password' => '$2y$10$qz/nF3ISDrIA9oGIpuCPdOSKgXSgvErCmBC56PUzW4G/gPwSVogiy',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-04 13:47:33',
                'updated_at' => '2023-08-04 13:47:33',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$GcdUe0prnchGgY0ZSvt6V.8jdifuDymA9ZTbX4ajurmHGMf06.9Ka',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$8ovhCYbqs0jFgwvZNKFAG.ct2gD.3pWiNo6.ArqlwnCn8.RmWvMAO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$K3vcFREuPirh6sMxCEa7FuorjuyoFeLVadJKOiR1KNHuefD7Uy1Q6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$2Ra4YbSdkjNAcqBZ4i9YM.4iEJvf2nYybUhTpGnxeVYINVriHwnFa',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Daniel Bennett',
                'email' => 'danielbennett@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:39:55',
                'password' => '$2y$10$gpRnCFrNYCCsz1N0oHrNMOnrLsEsfanEpm1oR1lEmnydbhTQriJfG',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:39:55',
                'updated_at' => '2023-08-07 13:39:55',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Amelia Justice',
                'email' => 'ameliajustice@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:54:13',
                'password' => '$2y$10$C09hyTponoaYsprV07hhgOQsBGq/G8F6Dm5uXa8bgs25hx.FX3cma',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:54:13',
                'updated_at' => '2023-08-07 13:54:13',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Amelia Justice',
                'email' => 'ameliajustice@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:54:13',
                'password' => '$2y$10$qAgez6N.evuPIlem7v3FlucysYwHZ8UE0mP6HRDTAt2TPq3X6YAQq',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:54:13',
                'updated_at' => '2023-08-07 13:54:13',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Thomas Bradford',
                'email' => 'thomasbradford@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:02:54',
                'password' => '$2y$10$.ryUIeqJhmDlL3uQFoz3kuT3aSEKUejAjP6TwrLaGeQDUBsU6mogS',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:02:54',
                'updated_at' => '2023-08-07 14:02:54',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Victoria Whitman',
                'email' => 'victoriawhitman@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:18:52',
                'password' => '$2y$10$wMuasJh04ASeaIFtreQiYOrswDQQa3QTX7knkakI/uCfgIjQ6zVeq',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:18:52',
                'updated_at' => '2023-08-07 14:18:52',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'James Thornton',
                'email' => 'jamesthornton@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:54:38',
                'password' => '$2y$10$tVCNgJIj9ujyjbnrga2pA.NM4mykULDg.JybWDxnxkt0.NTxNhGKG',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:54:38',
                'updated_at' => '2023-08-07 14:54:38',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Sophia Lancaster',
                'email' => 'sophialancaster@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 15:00:10',
                'password' => '$2y$10$lQhvKdq389hyp3.ndF82G.SA0hJotsSXOk27CBc9pjwRmC2yajl9C',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 15:00:10',
                'updated_at' => '2023-08-07 15:00:10',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Isabella Carrington',
                'email' => 'isabellacarrington@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 16:50:34',
                'password' => '$2y$10$5IyULRvJS69N/PTj2x4uOuZKS9pCXWjucSHOnloY0n.jthGFyWIVK',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 16:50:34',
                'updated_at' => '2023-08-07 16:50:34',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'adam shaw',
                'email' => 'adamshaw@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-09 09:16:12',
                'password' => '$2y$10$nVdhR0szeB7ztcSEPtuQDuFelvuITJfEouRKHGSr38msshQyzNRaK',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-09 09:16:11',
                'updated_at' => '2023-08-09 09:16:12',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'mono 1',
                'email' => 'mono@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-09 11:58:55',
                'password' => '$2y$10$skYkB8nrIp/OWLUUaqJnsu60zvk0iue0l4b0ug093gALcKR3oL5vm',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-09 11:58:55',
                'updated_at' => '2023-08-09 11:58:55',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Dean Jhon',
                'email' => 'dean@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 10:57:37',
                'password' => '$2y$10$eeq.1JEF4rj2o3PHEidN1uGNDHfTEM.LYhPnUTIMEVeWSxYpCBrpe',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 10:57:37',
                'updated_at' => '2023-09-27 10:57:37',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Jhon Dave',
                'email' => 'dave@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 11:57:09',
                'password' => '$2y$10$7Xj1s9D8COFhaNce5RdqdeBrXEfnj/X97Ro8X3QutzuPXDSd1278G',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 11:57:09',
                'updated_at' => '2023-09-27 11:57:09',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'john wick',
                'email' => 'johnwick@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 15:52:55',
                'password' => '$2y$10$oveJx77Vnz7FWfoEdyNLe.N/Hgu686jxU65OGY9deOJN6nVHUQiCu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 15:52:55',
                'updated_at' => '2023-09-27 15:52:55',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Trendingadvisor Law agency',
                'email' => 'info@trendingadvisor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 16:40:32',
                'password' => '$2y$10$/QFhRdu.iWaBFYxDX2htp.R9ioQ0Gwt5a.8C61Qq/wZBN7bZGSaEK',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-03 16:40:32',
                'updated_at' => '2023-10-03 16:40:32',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'muzamil younas',
                'email' => 'mistermuzammilyounas@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-04 16:54:09',
                'password' => '$2y$10$zl7PoTXNOkVhkYSfN98YEOSOyxICsTRY/3yxHoX0HSg228cszzyva',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-04 16:54:09',
                'updated_at' => '2023-10-04 16:55:43',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Cooper Hughes Law',
                'email' => 'Cooper@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 16:50:42',
                'password' => '$2y$10$FN4rLtkF.4eEZXBAz6E/jeRj72KY1k/LuEbl51FKMR4zX7Ce0CfP6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 16:50:42',
                'updated_at' => '2023-10-05 16:50:42',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Daniel Mitchell',
                'email' => 'DanielMitchell@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-04 23:09:39',
                'password' => '$2y$10$Ib7moxFwGR7g4NBMwaYVu.FkKR4nD.lpGfAWJi5/MloJJT0UAoMM2',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 17:52:54',
                'updated_at' => '2023-10-05 17:52:54',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Emily Davis',
                'email' => 'emily.davis@damylawfirm.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 19:10:50',
                'password' => '$2y$10$xID7H0vjOj9FcBaSxbOEzO0XHN7.6l/hOgiCwkJr0rwGcFHPzU7g6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:10:50',
                'updated_at' => '2023-10-05 19:10:50',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@example.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:56:11',
                'password' => '$2y$10$RB52bXJhhppquqqysrdnjOKTBq8rdUA9fnJIjCU3qMs23Ejs8uZ/a',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:41:45',
                'updated_at' => '2023-10-05 19:41:45',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Brown David',
                'email' => 'david.brown@example.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:56:16',
                'password' => '$2y$10$BN294RbOB05xuMDo1qn94e6fgltsPsMgUrfmOeYifR5Uq1haxvDRi',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:45:20',
                'updated_at' => '2023-10-05 19:45:20',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Benjamin Crawford',
                'email' => 'Benjamin@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:03:51',
                'password' => '$2y$10$ShbXfY5TgIHbpnInN.Q0j.0Ipu6pGqVspG4Xhl9bXMqd39XsDQNIW',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:20:52',
                'updated_at' => '2023-10-06 18:20:52',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'David Thompson',
                'email' => 'David@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:03:56',
                'password' => '$2y$10$HeriP.XxlLkPRH9I85RmUerKBsocwiNlJ8HL2bB1IvDasPbMSZlUO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:27:18',
                'updated_at' => '2023-10-06 18:27:18',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Jonathan Baker',
                'email' => 'Jonathan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:01',
                'password' => '$2y$10$Kp.03/wCqm9ESFKxgajIt.evcdAcfXfq9Y6XbCYTDLP8dKc3w5UTG',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:31:55',
                'updated_at' => '2023-10-06 18:31:55',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Sophia Martinez',
                'email' => 'Sophia@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:04',
                'password' => '$2y$10$bVH3EfxwnfJg6pKledh7RO.8YIdgDRt9iWHxWUyZxKPM.u2lJS4o.',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:43:04',
                'updated_at' => '2023-10-06 18:43:04',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Zoe Anderson',
                'email' => 'Zoe@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:07',
                'password' => '$2y$10$80HkCS82/h9im8dHU.q2rOD.Rqqc7idcGojBi1RGbQI2qx2aaFowe',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:46:21',
                'updated_at' => '2023-10-06 18:46:21',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Jessica Taylor',
                'email' => 'jessica@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 20:55:56',
                'password' => '$2y$10$n90aB7asRoi1SIGJrKmTEu2xcWzsd8IcdeyyV8w6rHECUN8dZ2OV6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-09 15:38:02',
                'updated_at' => '2023-10-09 15:38:02',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Laura Parker',
                'email' => 'laura@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 20:55:59',
                'password' => '$2y$10$HTuESKBzqKKA8KLxxraDquCgxy6EmPKH41FLU4/sYZuIPEx0kCNzK',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-09 15:41:32',
                'updated_at' => '2023-10-09 15:41:32',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'mark jhon',
                'email' => 'markjhon@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-12 12:50:15',
                'password' => '$2y$10$XpEM/MNnpgu1xCnYiGcfpOHj2YWX9WeEHumKKtw6OpX.2geNipE66',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-12 12:50:15',
                'updated_at' => '2023-10-12 12:50:15',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'jimmy m',
                'email' => 'jimmy@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-23 15:52:20',
                'password' => '$2y$10$Ql3fTN6zgZ/TU0IUnFD3auDyrMcf5CLuw8jQ9CLOcu3K3cSqwqMwS',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-23 15:52:20',
                'updated_at' => '2023-10-23 15:52:20',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Jackson Carter',
                'email' => 'jackson@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-25 22:40:13',
                'password' => '$2y$10$/o8W4UzrKRnqWX1Jvk3ZLeTA1AkJwV6OkReeKfOSg1Q/MlvOF/Qj2',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-23 17:37:04',
                'updated_at' => '2023-10-23 17:37:04',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 41,
                'name' => 'Faizan Fazal',
                'email' => 'subhansheikh12212@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-26 19:59:21',
                'password' => '$2y$10$Xh6BjyInnqXo1Pme5fTujOgLh89V3TUj6gtEphfHeg82GdADSATga',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-26 19:59:21',
                'updated_at' => '2023-10-26 19:59:21',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 43,
                'name' => 'james Andersion',
                'email' => 'james@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-03 16:19:51',
                'password' => '$2y$10$q/v89vChmN5O77rA53Pc1.gfJw7G3xJ/hKicsc6T.1wIxWpZJ6ZA.',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-03 16:19:51',
                'updated_at' => '2023-11-03 16:19:51',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 44,
                'name' => 'Alexander Hamilton',
                'email' => 'alexander.hamilton@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-14 14:49:33',
                'password' => '$2y$10$IEkwHIod6MSRcshNBgnUFOhgxusLk1CK/ysR5lF63jMwK557AkzIK',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-14 14:49:33',
                'updated_at' => '2023-11-14 14:49:33',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 45,
                'name' => 'Mahmoud ali',
                'email' => 'mly150779@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 02:19:00',
                'password' => '$2y$10$AUABIVb8NGNaBONCyPyVhedvbxFMPjkiwA/7Np0BHdnFtVqMghipO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 02:19:00',
                'updated_at' => '2023-11-23 02:19:00',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 46,
                'name' => 'JOse Luis Orbes',
                'email' => 'orbesjoe@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 04:50:21',
                'password' => '$2y$10$SOfHH9MBqwc2onfCUFBQ8uu8SJ1NQ8qac5DUt.f1MHSDCCzbYO2Qm',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 04:50:21',
                'updated_at' => '2023-11-23 04:50:21',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 47,
                'name' => 'vovo momo',
                'email' => 'superadmin@ramom.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 10:05:41',
                'password' => '$2y$10$nMfigjW7S9234.FAnm8o9OhbqMxiQuSG9MJ6bKx5nhepG2VgcpNxy',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 10:05:41',
                'updated_at' => '2023-11-23 10:05:41',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 48,
                'name' => 'dd dd',
                'email' => 'job_seeker@archielite.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 10:12:31',
                'password' => '$2y$10$U.nGCFzeWrohCb4uEb/wd.5KoWQiUC7UdLUzqaKKpLXaFQtInG1x.',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 10:12:31',
                'updated_at' => '2023-11-23 10:12:31',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 49,
                'name' => 'mahmoud subhy',
                'email' => 'mahmoud@mahmoud.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 13:48:49',
                'password' => '$2y$10$etrKcNyY.LgUza4nbZd3Ae41fPzyuFek2Svr4grSC5TvOOwJKkNAq',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 13:48:49',
                'updated_at' => '2023-11-23 13:48:49',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 50,
                'name' => 'ahmed ahmed',
                'email' => 'ahmed@ahmed.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 14:12:18',
                'password' => '$2y$10$QzvYYgZNTNvoGsU1A6qmZu2jfFcsBHohElaxVkraaxRYjQ8t4gC6u',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 14:12:18',
                'updated_at' => '2023-11-23 14:12:18',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 51,
                'name' => 'panorama alqassim',
                'email' => 'alqassimpanorama@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 14:27:30',
                'password' => '$2y$10$KWiInqMihPUcpUQpwbErAO4cZGfxmh4jyScq7h3b/ZdMmBFbi3pIC',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 14:27:30',
                'updated_at' => '2023-11-23 14:27:30',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 52,
                'name' => 'panorama alqassim',
                'email' => 'mohamed@mohamed.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Xyg5DL5RmPHZ4TaocrWW1OIW5xxv7Zh4RXP1v1tmPPgn/NU8Mkl6y',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 14:34:31',
                'updated_at' => '2023-11-23 14:34:31',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 53,
                'name' => 'sina najafi',
                'email' => 'djcincinati@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 16:10:23',
                'password' => '$2y$10$ND6t7bVVql.vMJPOnvEPculbSo1TOLTeOb/kDrsTxDDiWHVFz/lnu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 16:10:23',
                'updated_at' => '2023-11-23 16:10:23',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 54,
                'name' => 'sinasi sinasi',
                'email' => 'sina@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 16:15:35',
                'password' => '$2y$10$NoC3375i.dR2jT5c95PBkOqsUWL6dMYcGXR1pntsL3YSLH.AvgaNa',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 16:15:35',
                'updated_at' => '2023-11-23 16:15:35',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 55,
                'name' => 'test test',
                'email' => 'test@test.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 18:20:32',
                'password' => '$2y$10$WEXrHhMiAZe5Asle7Zj5rOoQeHOgAqTMjgicXR0SQ3SCUlJ4uF4Zm',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 18:20:32',
                'updated_at' => '2023-11-23 18:20:32',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 56,
                'name' => 'Jack Ma',
                'email' => 'jackma@test.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 18:27:19',
                'password' => '$2y$10$EMomQyw53SnvNHJpOGa5dekGV0IRg36QXvMdWQ0pnEZVkWLRxMDqy',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 18:27:19',
                'updated_at' => '2023-11-23 18:27:19',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 57,
                'name' => 'Seeker User',
                'email' => 'seeker@user.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 18:30:50',
                'password' => '$2y$10$IQml9YReEkGS0wCUD8kRSuP5MgVJB9YOX7ama2jRDMp/YebCqwFU6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 18:30:50',
                'updated_at' => '2023-11-23 18:30:50',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 58,
                'name' => 'Consultant Lawyer',
                'email' => 'consultant@lawyer.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 18:32:53',
                'password' => '$2y$10$cCCjbt1e9QBXg3zlwPPNpeI7nSS7vnjwNBf0MyeCQci7/W8sDbI1e',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 18:32:53',
                'updated_at' => '2023-11-23 18:32:53',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 59,
                'name' => 'Uu Jj',
                'email' => 'hvnj@ggf.comcom',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-24 02:48:59',
                'password' => '$2y$10$TTK8/ns58/qJ4a935xLG7.6BsFYIr74un/NaJxRd8Ge6tuH8A00DW',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-24 02:48:59',
                'updated_at' => '2023-11-24 02:48:59',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 60,
                'name' => 'Abrham Assefa',
                'email' => 'mobtendersdata@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-24 19:12:59',
                'password' => '$2y$10$x8hKH.HoCf5tNjICxpNE8.F9xalbZ91CE8WfsFhHJrDCdsBQHukAa',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-24 19:12:59',
                'updated_at' => '2023-11-24 19:12:59',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 61,
                'name' => 'leo Nardo',
                'email' => 'leonardowilliams22@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-02 14:07:38',
                'password' => '$2y$10$n3RMyQp14hL82wxiWzhc7er24M6KdNToMd9p.MXcq8d1jC1XfUrNe',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-02 14:07:38',
                'updated_at' => '2023-12-02 14:07:38',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 62,
                'name' => 'Leo Nardo',
                'email' => 'leonardombangata@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-02 14:11:22',
                'password' => '$2y$10$QqiHPCNNrMd5B/ZSsOD8mOZBdrTtxzid9TR7wekMp/gMilUMswkZm',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-02 14:11:22',
                'updated_at' => '2023-12-02 14:11:22',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 63,
                'name' => 'Daniel Starred',
                'email' => 'danielstarred@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-03 23:15:32',
                'password' => '$2y$10$Fn6JRFu.QdQG6p4H5GyyeuQturGG11xzhpqaHYU1afG5zG4nPzo7a',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-03 23:15:32',
                'updated_at' => '2023-12-03 23:15:32',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 64,
                'name' => 'Faizan Fazal',
                'email' => 'faizan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-06 17:11:50',
                'password' => '$2y$10$ak4FVh/UZxF2/p9je2xeZu88YYe222q3EGbX0NE4s83oZMx7J1Fq6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-06 17:11:50',
                'updated_at' => '2023-12-06 17:11:50',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 65,
                'name' => 'KARAKKEEL SARITH',
                'email' => 'shouvith@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-07 18:01:53',
                'password' => '$2y$10$i3a1chATXwhBqecEPrq11OOOTlkEejqCLSo8.EhpsaYVZeF/aRDxu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-07 18:01:53',
                'updated_at' => '2023-12-07 18:01:53',
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'id' => 66,
                'name' => 'nik roy',
                'email' => 'nikitajmk555@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-09 13:11:15',
                'password' => '$2y$10$Y6VTLhkB6A0AgBw6ngfu6OWqBcCkj1q.cQtIOjXe1GLUXxCao0UFO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-09 13:11:15',
                'updated_at' => '2023-12-09 13:11:15',
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'id' => 67,
                'name' => 'odind odjdj',
                'email' => 'odincewebs@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-11 17:22:48',
                'password' => '$2y$10$R41R6Xkw.5MQvYbPIEkgIumPR0HlKUOfC.5IEsXc6966JAyI3yjU6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-11 17:22:48',
                'updated_at' => '2023-12-11 17:22:48',
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'id' => 68,
                'name' => 'dagi abea',
                'email' => 'dagiabea4@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-14 00:11:38',
                'password' => '$2y$10$rKzdNP5AYqdvoZNLY8nay.T7JCHpe/I7BeRJPZ4IlTZHfCtwIUrwu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-14 00:11:38',
                'updated_at' => '2023-12-14 00:11:38',
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'id' => 69,
                'name' => 'da advisor',
                'email' => 'dagiabea5@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-14 00:25:05',
                'password' => '$2y$10$NaLVkiNbXXu2EykE/T6T2OHXNDzXfxQMswkL0ajPwHiKbz6ZrTO22',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-14 00:25:05',
                'updated_at' => '2023-12-14 00:25:05',
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'id' => 70,
                'name' => 'n n',
                'email' => 'luxumatic@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-18 16:36:11',
                'password' => '$2y$10$OAyptPoCa.lUSr.GOYjaFODRGiAFaHqL.pEfpCtIk/jnaa8rVyUTS',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-18 16:36:11',
                'updated_at' => '2023-12-18 16:36:11',
                'deleted_at' => NULL,
            ),
            68 =>
            array (
                'id' => 71,
                'name' => 'da gi',
                'email' => 'dagiabea6@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-21 21:49:18',
                'password' => '$2y$10$h3NCubLxP9EE2/NJ4ERFvutct5ITo1loWgL9IARTiuCogmR7p3nEO',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-21 21:49:18',
                'updated_at' => '2023-12-21 21:49:18',
                'deleted_at' => NULL,
            ),
            69 =>
            array (
                'id' => 72,
                'name' => 'nhat nho',
                'email' => 'pnam749@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-22 07:26:15',
                'password' => '$2y$10$YtTfixij7pI1jlOFfSUxAeE4yH4NS9r6sjiKO.bEdlwA1y0oFvFDS',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-22 07:26:15',
                'updated_at' => '2023-12-22 07:26:15',
                'deleted_at' => NULL,
            ),
            70 =>
            array (
                'id' => 73,
                'name' => 'dagi abea',
                'email' => 'dagi.abea4@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-22 17:35:16',
                'updated_at' => '2023-12-22 17:35:16',
                'deleted_at' => NULL,
            ),
            71 =>
            array (
                'id' => 74,
                'name' => 'da ty',
                'email' => 'dagi@gmail.co',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-22 17:36:02',
                'password' => '$2y$10$LZy..M/oEx1XctXFQl488uUtrVLO9E9RZqymyOEi/8TSxnz66i08C',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-22 17:36:02',
                'updated_at' => '2023-12-22 17:36:02',
                'deleted_at' => NULL,
            ),
            72 =>
            array (
                'id' => 75,
                'name' => 'Thanh Dao',
                'email' => 'admin@bixso.vn',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-23 06:21:48',
                'password' => '$2y$10$SOwaeRh5PfTXBPoeaRyK9O38gchKiJ/mfs72EEwuSuSiOEpKOLsV2',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-23 06:21:48',
                'updated_at' => '2023-12-23 06:21:48',
                'deleted_at' => NULL,
            ),
            73 =>
            array (
                'id' => 76,
                'name' => 'Trung Dao',
                'email' => 'thanhtdao85@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-23 06:24:13',
                'password' => '$2y$10$uQI2NQm3XTlOVC.BAOlwpeiloHPmOIt6uIVuO1OgH/15rHkBIae6S',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-23 06:24:13',
                'updated_at' => '2023-12-23 06:24:13',
                'deleted_at' => NULL,
            ),
            74 =>
            array (
                'id' => 77,
                'name' => 'nguyen nhat',
                'email' => 'nhatmeo2102@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-24 12:59:22',
                'password' => '$2y$10$RZNwX88aXEOJ5vDWOBW2GeQyf8LMAVdF8zhk0zgmMwK3ngKF/wlia',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-24 12:59:22',
                'updated_at' => '2023-12-24 12:59:22',
                'deleted_at' => NULL,
            ),
            75 =>
            array (
                'id' => 78,
                'name' => 'Dag Ab',
                'email' => 'admin@admin.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-24 16:14:16',
                'password' => '$2y$10$mfP5O9WFa8JcECNrXdmK4umhHlzzEW3sO0gIfPsMxvwsmpaMVr1v6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-24 16:14:15',
                'updated_at' => '2023-12-24 16:14:16',
                'deleted_at' => NULL,
            ),
            76 =>
            array (
                'id' => 79,
                'name' => 'nhat nem',
                'email' => 'nhatnhinho321@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-25 13:46:08',
                'password' => '$2y$10$X7ROqXzePd4rI.HzsdjHeOle7ZGcikcciRQA7bJ/sUPGVZaUI2W/G',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-25 13:46:08',
                'updated_at' => '2023-12-25 13:46:08',
                'deleted_at' => NULL,
            ),
            77 =>
            array (
                'id' => 80,
                'name' => 'bala chandhar',
                'email' => 'b.balachandhar@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-12-30 10:23:07',
                'password' => '$2y$10$KbvZtUbZ5qFxfwrREbi1d.6s0f7MEhNsyafvFmWMdZS/nzrMmQwPa',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-12-30 10:23:07',
                'updated_at' => '2023-12-30 10:23:07',
                'deleted_at' => NULL,
            ),
            78 =>
            array (
                'id' => 81,
                'name' => 'Ha Thái',
                'email' => 'thaikhanhha.tdtu@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-02 07:03:46',
                'password' => '$2y$10$9K4VKgH6OlA08JO66yVTduS.LruIimF.hZKSD/1UQ.jFpNsoOZ1m.',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-02 07:03:46',
                'updated_at' => '2024-01-02 07:03:46',
                'deleted_at' => NULL,
            ),
            79 =>
            array (
                'id' => 82,
                'name' => 'Deva gavli',
                'email' => 'signthedreams@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-03 12:08:17',
                'password' => '$2y$10$JqNZqyl.liuHRtt/aSG3XOw.4XJi8QrgUuPM.8rcsc5hnO37vLBm6',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-03 12:08:17',
                'updated_at' => '2024-01-03 12:08:17',
                'deleted_at' => NULL,
            ),
            80 =>
            array (
                'id' => 83,
                'name' => 'Bui Chan',
                'email' => 'buinguyenbinhchan1807@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-03 13:44:06',
                'password' => '$2y$10$EwGtx.vW4qD0flnolJH3JuznRlouy5T3u4nhe8I6Vhql/iifJEoHa',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-03 13:44:06',
                'updated_at' => '2024-01-03 13:44:06',
                'deleted_at' => NULL,
            ),
            81 =>
            array (
                'id' => 84,
                'name' => 'nhat nhat',
                'email' => 'nhat62480@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-04 12:54:23',
                'password' => '$2y$10$.9uZ01pmrtY7VxoDrBN9KeywrMQm7cp.9JIVnDgsS9cooQpxNUsDu',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-04 12:54:23',
                'updated_at' => '2024-01-04 12:54:23',
                'deleted_at' => NULL,
            ),
            82 =>
            array (
                'id' => 85,
                'name' => 'Thái Nguyễn',
                'email' => 'nguyenquocthai.180520012017@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-04 14:00:55',
                'password' => '$2y$10$KbCzKgoiPfnzM40Gb8OIXu/cvdB15aqQtXJbR8MtWI8ADdElCuMUq',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-04 14:00:55',
                'updated_at' => '2024-01-04 14:00:55',
                'deleted_at' => NULL,
            ),
            83 =>
            array (
                'id' => 86,
                'name' => 'hisham alaimo',
                'email' => 'alihishammi90@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-06 15:46:34',
                'password' => '$2y$10$jA1T2jZROa1dr.gxNPQSOeXsyx/CGr8DL1sw5lojAKFUWLLJ/60ne',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-06 15:46:34',
                'updated_at' => '2024-01-06 15:46:34',
                'deleted_at' => NULL,
            ),
            84 =>
            array (
                'id' => 87,
                'name' => 'test luat',
                'email' => 'test@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-08 12:13:41',
                'password' => '$2y$10$IYNK.JmgXcDQ///EwOeOS.hBgB2CNhCgJqmARJBrOG/IhpaN.kPJS',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-08 12:13:41',
                'updated_at' => '2024-01-08 12:13:41',
                'deleted_at' => NULL,
            ),
            85 =>
            array (
                'id' => 88,
                'name' => 'test luat',
                'email' => 'test123@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-08 14:14:25',
                'password' => '$2y$10$lDK7fqNgvh6R57D.qMoEJe6uXiXGXIYF8UpvIXjTXXF469UWledaG',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-08 14:14:25',
                'updated_at' => '2024-01-08 14:14:25',
                'deleted_at' => NULL,
            ),
            86 =>
            array (
                'id' => 89,
                'name' => 'anamul haque',
                'email' => 'anamulhaque1757@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-09 04:19:11',
                'password' => '$2y$10$BOkpKW2YRMYCEonO6Fpy.eEdoD10bMWstFqqK8ZZVpg2ciQWiceOC',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-09 04:19:11',
                'updated_at' => '2024-01-09 04:19:11',
                'deleted_at' => NULL,
            ),
            87 =>
            array (
                'id' => 90,
                'name' => 'an ha',
                'email' => 'anamulhaque1757@gmail.comx',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-01-09 04:25:10',
                'password' => '$2y$10$AeJrSYl4DJ77508F.H7ElOBfsCBXSbqu7HFM8paPo.cSu/PEWZjtC',
                'role_id' => NULL,
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-01-09 04:25:10',
                'updated_at' => '2024-01-09 04:25:10',
                'deleted_at' => NULL,
            ),
            88 =>
            array (
                'id' => 91,
                'name' => 'Judith',
                'email' => 'nybofocu@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'role_id' => 21,
                'profile_image_path' => '/profile_images/1709204840dark logo.png',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-02-29 10:54:48',
                'updated_at' => '2024-02-29 11:33:45',
                'deleted_at' => NULL,
            ),
            89 =>
            array (
                'id' => 92,
                'name' => 'Damon',
                'email' => 'cahot@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'role_id' => 20,
                'profile_image_path' => '/profile_images/1709204510darklogo.png',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-02-29 11:01:50',
                'updated_at' => '2024-02-29 11:52:15',
                'deleted_at' => NULL,
            ),
            90 =>
            array (
                'id' => 93,
                'name' => 'Talha Tariq',
                'email' => 'talha@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$O8fK.1NjdxLZuFcx2BgoAe0D/ajDYmywtcV45dQRpKIGMAYkJzSMW',
                'role_id' => 19,
                'profile_image_path' => '/profile_images/17092081521059346395_179_0_2064_1414_1920x0_80_0_0_1577c72306d45f92df16ce9ee3e1728d.jpg',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-02-29 12:02:32',
                'updated_at' => '2024-02-29 12:02:32',
                'deleted_at' => NULL,
            ),
        ));


    }
}
